debug: true
storage:
  mysql:
    host: "localhost"
    database: "skyblock"
    username: "user"
    password: "password"
    port: 3306
    ssl: true
  redis:
    endpoint: "localhost"
    auth: false
    password: ""
    port: 6379
